name: Tests

on:
  pull_request:
    paths:
      - '**.py'
      - '!setup.py'
      - '.github/workflows/tests.yml'

jobs:
  django-tests:
    runs-on: ubuntu-latest
    name: Django Test Suite
    strategy:
      fail-fast: false
      matrix:
        pgver: [10, latest]
        #pgver: [latest]
        dbapidriver: [psycopg2, psycopg3]
        #dbapidriver: [psycopg3]
    services:
      postgres:
        image: postgres:${{ matrix.pgver }}
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    steps:
      - name: Checkout psycopg3
        if: ${{ matrix.dbapidriver == 'psycopg3' }}
        with:
          repository: 'psycopg/psycopg'
          ref: 'master'
          path: 'psycopg3_repo'
        uses: actions/checkout@v2

      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout Django with my rebased changes
        uses: actions/checkout@v2
        with:
          repository: 'ramiro/django'
          ref: 'psycopg3-4.1'
          path: 'django_repo'

      #- name: Checkout Django with Daniele's changes
      #  uses: actions/checkout@v2
      #  with:
      #    repository: 'dvarrazzo/django'
      #    ref: 'psycopg3-4.1'
      #    path: 'django_repo'

      #- name: Checkout upstream Django
      #  uses: actions/checkout@v2
      #  with:
      #    repository: 'django/django'
      #    ref: 'main'
      #    #ref: '8b020f2e64f1cbf2b06205a389a13af6623f90ce'
      #    path: 'django_repo'

      - name: Install system packages for Django's Python test dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libmemcached-dev
      - name: Install Django and its Python test dependencies
        run: |
          cd django_repo/tests/
          pip3 install -e ..
          pip3 install -r requirements/py3.txt
          pip3 install -r requirements/postgres.txt
      - name: install the django-psycopg3 backend
        if: ${{ matrix.dbapidriver == 'psycopg3' }}
        run: pip3 install .
      - name: Copy test settings files
        run: cp .github/workflows/test_psycopg*.py django_repo/tests/
      #- name: Setup upterm session
      #  uses: lhotari/action-upterm@v1
      #  #with:
      #  #  ## limits ssh access and adds the ssh public key for the user which triggered the workflow
      #  #  limit-access-to-actor: true
      - name: Run the tests
        #run: python3 django_repo/tests/runtests.py --settings test_${{ matrix.dbapidriver }} -v 1 --parallel=1
        run: >
          python3 django_repo/tests/runtests.py --settings test_${{ matrix.dbapidriver }} -v 1 --parallel=1
          admin_changelist.tests.ChangeListTests
          aggregation.tests.AggregateTestCase
          m2m_recursive.tests.RecursiveM2MTests
          aggregation_regress.tests.AggregationTests
          fixtures_regress.tests.TestFixtures
          many_to_many.tests.ManyToManyTests
          postgres_tests.test_bulk_update.BulkSaveTests
          postgres_tests.test_hstore.SimpleTests
          postgres_tests.test_hstore.TestQuerying
          bulk_create.tests.BulkCreateTests
          annotations.tests.NonAggregateAnnotationTestCase
          migrations.test_operations.OperationTests
          fixtures.tests.FixtureLoadingTests
        #run: python3 django_repo/tests/runtests.py --settings test_${{ matrix.dbapidriver }} -v 1 --parallel=1 many_to_many.tests.ManyToManyTests.test_add
